version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "galafis"
    assignees:
      - "galafis"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "security"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Node.js dependencies (if applicable)
  - package-ecosystem: "npm"
    directory: "/ecommerce-dashboard"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "galafis"
    assignees:
      - "galafis"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"

  # Node.js dependencies for AI Assistant demo
  - package-ecosystem: "npm"
    directory: "/ai-assistant-demo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 5
    reviewers:
      - "galafis"
    assignees:
      - "galafis"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "demo"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
    open-pull-requests-limit: 5
    reviewers:
      - "galafis"
    assignees:
      - "galafis"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
